"""Add tax_exempt_cities table

Revision ID: 3cf3da059ef2
Revises: e4c8b81d3557
Create Date: 2025-07-29 23:38:05.776228

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3cf3da059ef2'
down_revision = 'e4c8b81d3557'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tax_exempt_cities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('city_name', sa.String(length=100), nullable=False),
    sa.Column('tax_discount_percent', sa.Float(), nullable=False),
    sa.Column('annual_cap', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('city_name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tax_exempt_cities')
    # ### end Alembic commands ###
