"""empty message

Revision ID: e4c8b81d3557
Revises: 7d89fc6b5db0
Create Date: 2025-07-29 22:11:16.800963

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e4c8b81d3557'
down_revision = '7d89fc6b5db0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('child',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('birth_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('gender', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('marital_status', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('city', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('has_degree', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('degree_year', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('degree_year')
        batch_op.drop_column('has_degree')
        batch_op.drop_column('city')
        batch_op.drop_column('marital_status')
        batch_op.drop_column('gender')
        batch_op.drop_column('birth_date')

    op.drop_table('child')
    # ### end Alembic commands ###
